---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage
resources:
- github.com/rancher/local-path-provisioner/deploy?ref=v0.0.19

images:
  - name: rancher/local-path-provisioner
    newTag: v0.0.19

patches:
  - target:
      kind: ConfigMap
      name: local-path-config
    path: configmap-patch.yaml