---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fopido-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/projects/secrets-overlay
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg

