---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 9.16.2
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      type: NodePort
      externalTrafficPolicy: Cluster
    ports:
      metrics:
        port: 8080
        expose: true
        protocol: TCP
    persistence:
      enabled: true
      storageClass: local-path
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=leonid.koftun@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.letsencrypt.acme.dnsChallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=inwx"
      - "--certificatesresolvers.letsencrypt2.acme.email=leonid.koftun@gmail.com"
      - "--certificatesresolvers.letsencrypt2.acme.storage=/data/acme-tls.json"
      - "--certificatesresolvers.letsencrypt2.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt2.acme.tlschallenge=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=:443"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--log.level=INFO"
    env:
      - name: INWX_USERNAME
        valueFrom:
          secretKeyRef:
            name: inwx
            key: username
      - name: INWX_PASSWORD
        valueFrom:
          secretKeyRef:
            name: inwx
            key: password
