---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.2.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        ingress.kubernetes.io/ssl-force-host: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - grafana.sldk.de
    persistence:
      enabled: true
      size: 500Mi
      # FIXME not managed by gotk
      existingClaim: grafana-pvc
    securityContext: { "runAsUser": 0, "fsGroup": 0 }
    plugins:
      - grafana-piechart-panel
    grafana.ini:
      server:
        root_url: https://grafana.sldk.de
    # TODO dashboard provisioning and stuff
