apiVersion: apps/v1
kind: Deployment
metadata:
  name: fopido
spec:
  selector:
    matchLabels:
      app: fopido
  replicas: 1
  template:
    metadata:
      labels:
        app: fopido
    spec:
      containers:
        - name: fopido
          image: ghcr.io/sladkoff/fopido:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
