---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 13.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    grafana:
      replicas: 1
      persistence:
        enabled: true
        storageClassName: local-path
      admin:
        existingSecret: grafana
        userKey: admin-user
        passwordKey: admin-password
    alertmanager:
      replicas: 1
    prometheus:
      replicas: 1
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false