---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 13.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    grafana:
      replicas: 1
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          ingress.kubernetes.io/ssl-force-host: "true"
          ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - grafana.sldk.de
    alertmanager:
      replicas: 1
    prometheus:
      replicas: 1