---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: clavis
spec:
  entryPoints:
    - websecure
  middlewares:
    - https-redirectscheme
  routes:
    - match: Host(`www.fortepiano-unterricht.de`)
      kind: Rule
      services:
        - name: clavis
          port: 80
  tls:
    certResolver: letsencrypt
