apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - deployment.yaml
  - service.yaml

namespace: clavis

images:
  - name: ghcr.io/sladkoff/clavis
    newTag: 1.0.0
