---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fopido-mariadb
  namespace: fopido
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    primary:
      persistence:
        enabled: true
        existingClaim: fopido-pvc
    auth:
      database: fopido_prod
      username: fopido_user
      existingSecret: fopido-mariadb