---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: fopido-pv
  namespace: fopido
  labels:
    type: local
    app: fopido
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/k8s_volumes/fopido-legacy"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fopido-pvc
  namespace: fopido
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: fopido