apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

- helmrepositories/bitnami-charts.yaml
- helmrepositories/prometheus-community-charts.yaml
