apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- secrets/fopido-git-secret.yaml
- helmrepositories/bitnami-charts.yaml
- gotk-fopido-source.yaml
- gotk-fopido-kustomization.yaml