apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- helmrepositories/bitnami-charts.yaml

- kustomizations/gotk-fopido-kustomization.yaml
- kustomizations/gotk-fopido-secrets-kustomization.yaml
- kustomizations/gotk-clavis-kustomization.yaml