---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kigana-web
spec:
  selector:
    matchLabels:
      app: kigana-web
  replicas: 2
  template:
    metadata:
      labels:
        app: kigana-web
    spec:
      containers:
        - name: kigana-web
          image: ghcr.io/kigana/kigana-web:latest
          env:
            - name: AUTH0_BASE_URL
              value: 'https://kigana.com'
            - name: AUTH0_ISSUER_BASE_URL
              value: 'https://kigana-dev.eu.auth0.com'
            - name: AUTH0_CLIENT_ID
              value: 'PrQFZ8NneyG4wItHScHDaSYTJ5bhR1YQ'
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: kigana-secret
                  key: auth0-secret
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kigana-secret
                  key: auth0-client-secret
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: github-container-registry
