name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1

      - name: Build flux-like kustomization
        run: cd ./cluster && kustomize create --autodetect --recursive && kustomize build ./cluster > ./cluster.yaml
        
      - uses: actions/upload-artifact@v2
        with:
          name: cluster.yml
          path: ./cluster.yaml
          
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: cluster.yml
          path: ./cluster.yaml

      - name: Run kubeval
        run: kubeval --ignore-missing-schemas ./cluster.yaml
        
  kube-score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: cluster.yml
          path: ./cluster.yaml

      - name: Run kube-score
        run: |
          wget -q -O ./kube-score https://github.com/zegl/kube-score/releases/download/v1.10.1/kube-score_1.10.1_linux_amd64 && \
            chmod +x ./kube-score && \
            kustomize build ./cluster | ./kube-score score -
