name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1
      - uses: lra/setup-kubeval@v1.0.1

      - name: Build flux-like root kustomization
        run: cd ./cluster && kustomize create --autodetect --recursive

      - name: Run kubeval
        run: kustomize build ./cluster | kubeval --ignore-missing-schemas
        
      - name: Run kube-score
        run: |
          wget -O ./kube-score https://github.com/zegl/kube-score/releases/download/v1.10.1/kube-score_1.10.1_linux_amd64 && \
            chmod +x ./kube-score && \
            kustomize build ./cluster | ./kube-score score -
